[project]
name = "codeexec"
version = "0.1.0"
description = "provide code execution as a tool for an AI mode"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docker>=7.1.0",
    "fastmcp==2.6.1",
    "mcp[cli]>=1.14.1",
]
